// apps/artisan/src/lib/icon-a11y.test.ts
//
// The accessible-name contract for the asset packs, verified by rendering.
//
// This exists because the failure it guards is invisible to every other gate.
// The SVG components are generated by @poppanator/sveltekit-svg as
// `<svg {...props}>{@html contents}</svg>` -- there is no slot. The original
// Icon and Illustration components passed a <title> element as a CHILD and
// pointed aria-labelledby at its id. The child was silently discarded, so the
// attribute referenced an id that was never in the document. A dangling
// aria-labelledby computes to an EMPTY accessible name: the icon announces as
// an unlabelled graphic while the source looks correct, and the build,
// svelte-check and eslint all pass.
//
// So: assert the computed name, not the markup.

import { describe, expect, it } from 'vitest';
import { render } from '@testing-library/svelte';
import { Icon } from '@kalakriti/icons';
import { Illustration } from '@kalakriti/illustrations';

describe('Icon', () => {
  it('exposes `title` as the accessible name', () => {
    const { getByRole } = render(Icon, { name: 'search', title: 'Search listings' });
    const svg = getByRole('img', { name: 'Search listings' });

    expect(svg.getAttribute('aria-label')).toBe('Search listings');
    // If this ever comes back, so does the dangling-reference bug.
    expect(svg.getAttribute('aria-labelledby')).toBeNull();
    expect(svg.querySelector('title')).toBeNull();
  });

  it('is hidden from assistive tech when no title is given', () => {
    const { container } = render(Icon, { name: 'search' });
    const svg = container.querySelector('svg');

    expect(svg?.getAttribute('aria-hidden')).toBe('true');
    expect(svg?.getAttribute('focusable')).toBe('false');
    expect(svg?.getAttribute('role')).toBeNull();
  });

  it('renders the icon named, not a fallback', () => {
    const { container } = render(Icon, { name: 'camera' });
    // Every icon in the set is a 24x24 stroke drawing; a missing component
    // renders nothing at all, which is the regression worth catching.
    expect(container.querySelector('svg')?.getAttribute('viewBox')).toBe('0 0 24 24');
  });
});

describe('Illustration', () => {
  it('exposes `title` as the accessible name', () => {
    const { getByRole } = render(Illustration, {
      name: 'empty-no-listings',
      title: 'No listings yet',
    });
    const svg = getByRole('img', { name: 'No listings yet' });

    expect(svg.getAttribute('aria-label')).toBe('No listings yet');
    expect(svg.getAttribute('aria-labelledby')).toBeNull();
  });

  it('is decorative by default, since the surrounding copy carries the meaning', () => {
    const { container } = render(Illustration, { name: 'empty-no-listings' });
    expect(container.querySelector('svg')?.getAttribute('aria-hidden')).toBe('true');
  });
});
