// services/channel-svc/internal/channel/sqlc/models.go

// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Notification struct {
	ID          uuid.UUID
	RecipientID string
	Kind        string
	Language    string
	Title       string
	Body        string
	Payload     []byte
	ReadAt      sql.NullTime
	CreatedAt   time.Time
}

type NotificationDelivery struct {
	ID             uuid.UUID
	NotificationID uuid.UUID
	Channel        string
	Recipient      string
	Status         string
	AttemptCount   int32
	LastError      sql.NullString
	SentAt         sql.NullTime
	CreatedAt      time.Time
}

type Follow struct {
	ArtisanID  uuid.UUID
	FollowerID string
	Source     string
	CreatedAt  time.Time
}
