// services/channel-svc/internal/channel/sqlc/notification_delivery.sql.go

// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const insertNotificationDelivery = `-- name: InsertNotificationDelivery :one
INSERT INTO notification_delivery (id, notification_id, channel, recipient, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, notification_id, channel, recipient, status, attempt_count, last_error, sent_at, created_at
`

type InsertNotificationDeliveryParams struct {
	ID             uuid.UUID
	NotificationID uuid.UUID
	Channel        string
	Recipient      string
	Status         string
	CreatedAt      time.Time
}

func (q *Queries) InsertNotificationDelivery(ctx context.Context, arg InsertNotificationDeliveryParams) (NotificationDelivery, error) {
	row := q.db.QueryRowContext(ctx, insertNotificationDelivery,
		arg.ID,
		arg.NotificationID,
		arg.Channel,
		arg.Recipient,
		arg.Status,
		arg.CreatedAt,
	)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Channel,
		&i.Recipient,
		&i.Status,
		&i.AttemptCount,
		&i.LastError,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateDeliveryStatus = `-- name: UpdateDeliveryStatus :exec
UPDATE notification_delivery
SET status = $2, sent_at = $3, attempt_count = attempt_count + 1, last_error = $4
WHERE id = $1
`

type UpdateDeliveryStatusParams struct {
	ID        uuid.UUID
	Status    string
	SentAt    sql.NullTime
	LastError sql.NullString
}

func (q *Queries) UpdateDeliveryStatus(ctx context.Context, arg UpdateDeliveryStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeliveryStatus,
		arg.ID,
		arg.Status,
		arg.SentAt,
		arg.LastError,
	)
	return err
}

const getDeliveriesForNotification = `-- name: GetDeliveriesForNotification :many
SELECT id, notification_id, channel, recipient, status, attempt_count, last_error, sent_at, created_at FROM notification_delivery
WHERE notification_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetDeliveriesForNotification(ctx context.Context, notificationID uuid.UUID) ([]NotificationDelivery, error) {
	rows, err := q.db.QueryContext(ctx, getDeliveriesForNotification, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationDelivery
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.Channel,
			&i.Recipient,
			&i.Status,
			&i.AttemptCount,
			&i.LastError,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
