// services/channel-svc/internal/channel/sqlc/social.sql.go

// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notification (id, recipient_id, kind, language, title, body, payload, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, recipient_id, kind, language, title, body, payload, read_at, created_at
`

type InsertNotificationParams struct {
	ID          uuid.UUID
	RecipientID string
	Kind        string
	Language    string
	Title       string
	Body        string
	Payload     []byte
	CreatedAt   time.Time
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, insertNotification,
		arg.ID,
		arg.RecipientID,
		arg.Kind,
		arg.Language,
		arg.Title,
		arg.Body,
		arg.Payload,
		arg.CreatedAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.Kind,
		&i.Language,
		&i.Title,
		&i.Body,
		&i.Payload,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNotification = `-- name: GetNotification :one
SELECT id, recipient_id, kind, language, title, body, payload, read_at, created_at FROM notification WHERE id = $1
`

func (q *Queries) GetNotification(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.Kind,
		&i.Language,
		&i.Title,
		&i.Body,
		&i.Payload,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationsForUser = `-- name: ListNotificationsForUser :many
SELECT id, recipient_id, kind, language, title, body, payload, read_at, created_at FROM notification
WHERE recipient_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsForUserParams struct {
	RecipientID string
	Limit       int32
	Offset      int32
}

func (q *Queries) ListNotificationsForUser(ctx context.Context, arg ListNotificationsForUserParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsForUser, arg.RecipientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.Kind,
			&i.Language,
			&i.Title,
			&i.Body,
			&i.Payload,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listUnreadNotificationsForUser = `-- name: ListUnreadNotificationsForUser :many
SELECT id, recipient_id, kind, language, title, body, payload, read_at, created_at FROM notification
WHERE recipient_id = $1 AND read_at IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type ListUnreadNotificationsForUserParams struct {
	RecipientID string
	Limit       int32
}

func (q *Queries) ListUnreadNotificationsForUser(ctx context.Context, arg ListUnreadNotificationsForUserParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listUnreadNotificationsForUser, arg.RecipientID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.Kind,
			&i.Language,
			&i.Title,
			&i.Body,
			&i.Payload,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notification
SET read_at = $2
WHERE id = $1 AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID
	ReadAt sql.NullTime
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationRead, arg.ID, arg.ReadAt)
	return err
}

const countUnreadForUser = `-- name: CountUnreadForUser :one
SELECT count(*) FROM notification
WHERE recipient_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadForUser(ctx context.Context, recipientID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadForUser, recipientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFollowers = `-- name: GetFollowers :many
SELECT follower_id FROM follow
WHERE artisan_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetFollowers(ctx context.Context, artisanID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getFollowers, artisanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var follower_id string
		if err := rows.Scan(&follower_id); err != nil {
			return nil, err
		}
		items = append(items, follower_id)
	}
	return items, rows.Err()
}
