// Generated by scripts/gen-batch4.mjs — do not hand-edit.
// A name outside this union is a compile error at every <Icon name="..."> call site.
export type IconName =
  | 'home'
  | 'search'
  | 'voice-search'
  | 'microphone'
  | 'camera'
  | 'video'
  | 'image'
  | 'upload'
  | 'plus'
  | 'edit'
  | 'trash'
  | 'check'
  | 'close'
  | 'chevron-up'
  | 'chevron-down'
  | 'chevron-left'
  | 'chevron-right'
  | 'arrow-up'
  | 'arrow-down'
  | 'arrow-left'
  | 'arrow-right'
  | 'filter'
  | 'sort'
  | 'share'
  | 'download'
  | 'print'
  | 'link'
  | 'external-link'
  | 'settings'
  | 'user'
  | 'users'
  | 'bell'
  | 'message'
  | 'whatsapp'
  | 'calendar'
  | 'clock'
  | 'location'
  | 'phone'
  | 'info'
  | 'warning'
  | 'error'
  | 'success'
  | 'help'
  | 'menu'
  | 'more-horizontal'
  | 'more-vertical'
  | 'eye'
  | 'eye-off'
  | 'lock'
  | 'refresh'
  | 'sync'
  | 'offline'
  | 'wifi-off'
  | 'language'
  | 'accessibility'
  | 'text-size'
  | 'contrast'
  | 'play'
  | 'pause'
  | 'volume'
  | 'speaker'
  | 'handmade-certified'
  | 'verified-artisan'
  | 'gi-tagged'
  | 'made-to-order'
  | 'ready-stock'
  | 'process-video'
  | 'provenance'
  | 'handloom-verified'
  | 'collective-order'
  | 'fair-price'
  | 'income-statement'
  | 'cluster'
  | 'shg'
  | 'dying-craft'
  | 'weaving'
  | 'block-printing'
  | 'pottery'
  | 'metalwork'
  | 'woodwork'
  | 'embroidery'
  | 'painting'
  | 'basketry'
  | 'jewellery'
  | 'leather'
  | 'stone'
  | 'bamboo'
  | 'charkha-spinner'
  | 'upload-zone';

/*
 * Component declarations for the barrel (index.js). Without these, TypeScript
 * sees a .js barrel re-exporting .svelte files and resolves the named exports
 * to nothing, so `import { Icon } from '@kalakriti/icons'` fails to type even
 * though it runs. Written by hand rather than generated: there are three
 * components and they change roughly never.
 */
import type { Component } from 'svelte';

export interface IconProps {
  name: IconName;
  /** Accessible name. Omit for a decorative icon (aria-hidden). */
  title?: string;
  /** Any CSS length, e.g. "1.5rem". */
  size?: string;
  /** 1.25 (dense) / 1.5 (default) / 2 (bold). */
  strokeWidth?: number;
  class?: string;
  [key: string]: unknown;
}

export interface SpinnerProps {
  /** 0-1, or omitted for indeterminate. Must come from real state. */
  progress?: number;
  title?: string;
  [key: string]: unknown;
}

export interface UploadZoneProps {
  state?: 'idle' | 'drag' | 'uploading' | 'success' | 'error';
  [key: string]: unknown;
}

export const Icon: Component<IconProps>;
export const Spinner: Component<SpinnerProps>;
export const UploadZone: Component<UploadZoneProps>;

export interface IconManifestEntry {
  name: IconName;
  category: string;
  file: string;
}
export const ICONS: readonly IconManifestEntry[];
