/* Generated by scripts/gen-batch4.mjs — do not hand-edit.
   Name -> component map for <Icon name="...">. Importing this file pulls in
   every icon; import a single ./src/<name>.svg directly when tree-shaking
   a specific icon matters (see README). */

import Icon_home from './src/home.svg';
import Icon_search from './src/search.svg';
import Icon_voice_search from './src/voice-search.svg';
import Icon_microphone from './src/microphone.svg';
import Icon_camera from './src/camera.svg';
import Icon_video from './src/video.svg';
import Icon_image from './src/image.svg';
import Icon_upload from './src/upload.svg';
import Icon_plus from './src/plus.svg';
import Icon_edit from './src/edit.svg';
import Icon_trash from './src/trash.svg';
import Icon_check from './src/check.svg';
import Icon_close from './src/close.svg';
import Icon_chevron_up from './src/chevron-up.svg';
import Icon_chevron_down from './src/chevron-down.svg';
import Icon_chevron_left from './src/chevron-left.svg';
import Icon_chevron_right from './src/chevron-right.svg';
import Icon_arrow_up from './src/arrow-up.svg';
import Icon_arrow_down from './src/arrow-down.svg';
import Icon_arrow_left from './src/arrow-left.svg';
import Icon_arrow_right from './src/arrow-right.svg';
import Icon_filter from './src/filter.svg';
import Icon_sort from './src/sort.svg';
import Icon_share from './src/share.svg';
import Icon_download from './src/download.svg';
import Icon_dollar_sign from './src/dollar-sign.svg';
import Icon_print from './src/print.svg';
import Icon_link from './src/link.svg';
import Icon_external_link from './src/external-link.svg';
import Icon_settings from './src/settings.svg';
import Icon_user from './src/user.svg';
import Icon_users from './src/users.svg';
import Icon_bell from './src/bell.svg';
import Icon_message from './src/message.svg';
import Icon_package from './src/package.svg';
import Icon_whatsapp from './src/whatsapp.svg';
import Icon_calendar from './src/calendar.svg';
import Icon_clock from './src/clock.svg';
import Icon_location from './src/location.svg';
import Icon_phone from './src/phone.svg';
import Icon_info from './src/info.svg';
import Icon_warning from './src/warning.svg';
import Icon_error from './src/error.svg';
import Icon_success from './src/success.svg';
import Icon_help from './src/help.svg';
import Icon_menu from './src/menu.svg';
import Icon_more_horizontal from './src/more-horizontal.svg';
import Icon_more_vertical from './src/more-vertical.svg';
import Icon_eye from './src/eye.svg';
import Icon_eye_off from './src/eye-off.svg';
import Icon_lock from './src/lock.svg';
import Icon_refresh from './src/refresh.svg';
import Icon_sync from './src/sync.svg';
import Icon_offline from './src/offline.svg';
import Icon_wifi_off from './src/wifi-off.svg';
import Icon_language from './src/language.svg';
import Icon_accessibility from './src/accessibility.svg';
import Icon_text_size from './src/text-size.svg';
import Icon_contrast from './src/contrast.svg';
import Icon_play from './src/play.svg';
import Icon_pause from './src/pause.svg';
import Icon_volume from './src/volume.svg';
import Icon_speaker from './src/speaker.svg';
import Icon_badge_verified from './src/badge-verified.svg';
import Icon_badge_master from './src/badge-master.svg';
import Icon_badge_award from './src/badge-award.svg';
import Icon_badge_gi from './src/badge-gi.svg';
import Icon_badge_coordinator from './src/badge-coordinator.svg';
import Icon_badge_milestone from './src/badge-milestone.svg';
import Icon_badge_locked from './src/badge-locked.svg';
import Icon_handmade_certified from './src/handmade-certified.svg';
import Icon_verified_artisan from './src/verified-artisan.svg';
import Icon_gi_tagged from './src/gi-tagged.svg';
import Icon_made_to_order from './src/made-to-order.svg';
import Icon_ready_stock from './src/ready-stock.svg';
import Icon_process_video from './src/process-video.svg';
import Icon_provenance from './src/provenance.svg';
import Icon_handloom_verified from './src/handloom-verified.svg';
import Icon_collective_order from './src/collective-order.svg';
import Icon_fair_price from './src/fair-price.svg';
import Icon_income_statement from './src/income-statement.svg';
import Icon_cluster from './src/cluster.svg';
import Icon_shg from './src/shg.svg';
import Icon_dying_craft from './src/dying-craft.svg';
import Icon_weaving from './src/weaving.svg';
import Icon_block_printing from './src/block-printing.svg';
import Icon_pottery from './src/pottery.svg';
import Icon_metalwork from './src/metalwork.svg';
import Icon_woodwork from './src/woodwork.svg';
import Icon_embroidery from './src/embroidery.svg';
import Icon_painting from './src/painting.svg';
import Icon_basketry from './src/basketry.svg';
import Icon_jewellery from './src/jewellery.svg';
import Icon_leather from './src/leather.svg';
import Icon_stone from './src/stone.svg';
import Icon_bamboo from './src/bamboo.svg';
import Icon_charkha_spinner from './src/charkha-spinner.svg';
import Icon_upload_zone from './src/upload-zone.svg';
import Icon_badge from './src/badge.svg';

export const ICON_COMPONENTS = {
  'home': Icon_home,
  'search': Icon_search,
  'voice-search': Icon_voice_search,
  'microphone': Icon_microphone,
  'camera': Icon_camera,
  'video': Icon_video,
  'image': Icon_image,
  'upload': Icon_upload,
  'plus': Icon_plus,
  'edit': Icon_edit,
  'trash': Icon_trash,
  'check': Icon_check,
  'close': Icon_close,
  'chevron-up': Icon_chevron_up,
  'chevron-down': Icon_chevron_down,
  'chevron-left': Icon_chevron_left,
  'chevron-right': Icon_chevron_right,
  'arrow-up': Icon_arrow_up,
  'arrow-down': Icon_arrow_down,
  'arrow-left': Icon_arrow_left,
  'arrow-right': Icon_arrow_right,
  'filter': Icon_filter,
  'sort': Icon_sort,
  'share': Icon_share,
  'download': Icon_download,
  'dollar-sign': Icon_dollar_sign,
  'print': Icon_print,
  'link': Icon_link,
  'external-link': Icon_external_link,
  'settings': Icon_settings,
  'user': Icon_user,
  'users': Icon_users,
  'bell': Icon_bell,
  'message': Icon_message,
  'package': Icon_package,
  'whatsapp': Icon_whatsapp,
  'calendar': Icon_calendar,
  'clock': Icon_clock,
  'location': Icon_location,
  'phone': Icon_phone,
  'info': Icon_info,
  'warning': Icon_warning,
  'error': Icon_error,
  'success': Icon_success,
  'help': Icon_help,
  'menu': Icon_menu,
  'more-horizontal': Icon_more_horizontal,
  'more-vertical': Icon_more_vertical,
  'eye': Icon_eye,
  'eye-off': Icon_eye_off,
  'lock': Icon_lock,
  'refresh': Icon_refresh,
  'sync': Icon_sync,
  'offline': Icon_offline,
  'wifi-off': Icon_wifi_off,
  'language': Icon_language,
  'accessibility': Icon_accessibility,
  'text-size': Icon_text_size,
  'contrast': Icon_contrast,
  'play': Icon_play,
  'pause': Icon_pause,
  'volume': Icon_volume,
  'speaker': Icon_speaker,
  'badge-verified': Icon_badge_verified,
  'badge-master': Icon_badge_master,
  'badge-award': Icon_badge_award,
  'badge-gi': Icon_badge_gi,
  'badge-coordinator': Icon_badge_coordinator,
  'badge-milestone': Icon_badge_milestone,
  'badge-locked': Icon_badge_locked,
  'handmade-certified': Icon_handmade_certified,
  'verified-artisan': Icon_verified_artisan,
  'gi-tagged': Icon_gi_tagged,
  'made-to-order': Icon_made_to_order,
  'ready-stock': Icon_ready_stock,
  'process-video': Icon_process_video,
  'provenance': Icon_provenance,
  'handloom-verified': Icon_handloom_verified,
  'collective-order': Icon_collective_order,
  'fair-price': Icon_fair_price,
  'income-statement': Icon_income_statement,
  'cluster': Icon_cluster,
  'shg': Icon_shg,
  'dying-craft': Icon_dying_craft,
  'weaving': Icon_weaving,
  'block-printing': Icon_block_printing,
  'pottery': Icon_pottery,
  'metalwork': Icon_metalwork,
  'woodwork': Icon_woodwork,
  'embroidery': Icon_embroidery,
  'painting': Icon_painting,
  'basketry': Icon_basketry,
  'jewellery': Icon_jewellery,
  'leather': Icon_leather,
  'stone': Icon_stone,
  'bamboo': Icon_bamboo,
  'charkha-spinner': Icon_charkha_spinner,
  'upload-zone': Icon_upload_zone,
  'badge': Icon_badge,
};
