<!--
  Kalakriti <Icon /> — Batch 4, migrated to Svelte 5 runes in Batch 2 of the
  frontend track.

    <Icon name="search" />
    <Icon name="warning" title="Something needs attention" />
    <Icon name="trash" class="k-icon--bold" />

  Importing this component (or icons.js, which it uses) pulls in the whole
  icon set — the name lookup needs every component available to dispatch on.
  When only one or two icons are used on a route, import the .svg directly
  instead (`import Search from '@kalakriti/icons/src/search.svg'`) to keep
  that page's bundle to just those icons; see the package README.

  ACCESSIBLE NAME. Decorative by default (aria-hidden, focusable="false").
  Passing `title` switches to role="img" with aria-label.

  This used to render a <title> child and point aria-labelledby at it. It
  could not work: the SVG components are generated by
  @poppanator/sveltekit-svg as `<svg {...props}>{@html contents}</svg>` —
  there is no slot, so the <title> was silently dropped and aria-labelledby
  referenced an id that was never in the document. A dangling
  aria-labelledby is worse than no label, because the element announces as
  unlabelled while looking correct in the source. aria-label needs no child
  and is verified by Icon.test.js.

  `size` and `strokeWidth` are shorthand for the same icons.css custom
  properties the `k-icon--dense`/`k-icon--bold` classes set — use whichever
  reads better at the call site:

    <Icon name="trash" size="1.5rem" strokeWidth={2} />
-->
<script>
  import { ICON_COMPONENTS } from './icons.js';

  /**
   * @typedef {object} Props
   * @property {import('./icons.d.ts').IconName} name
   * @property {string} [title] Accessible name. Omit for a decorative icon.
   * @property {string} [size] Any CSS length, e.g. "1.5rem".
   * @property {number} [strokeWidth] 1.25 (dense) / 1.5 (default) / 2 (bold).
   * @property {string} [class]
   */

  /** @type {Props & Record<string, unknown>} */
  let { name, title, size, strokeWidth, class: className, ...rest } = $props();

  const Component = $derived(ICON_COMPONENTS[name]);

  const sizeStyle = $derived(
    [
      size ? `width:${size};height:${size}` : '',
      strokeWidth ? `--k-icon-stroke:${strokeWidth}` : '',
    ]
      .filter(Boolean)
      .join(';'),
  );

  $effect(() => {
    if (!Component) {
      console.warn(
        `<Icon name="${name}"> does not match any icon in packages/icons/manifest.js`,
      );
    }
  });
</script>

{#if Component}
  <Component
    class="k-icon {className || ''}"
    role={title ? 'img' : undefined}
    aria-label={title}
    aria-hidden={title ? undefined : 'true'}
    focusable="false"
    {...rest}
    style={sizeStyle || undefined}
  />
{/if}
