/* Generated by scripts/gen-batch4.mjs — do not hand-edit.
   Icon manifest for the documentation site and the validation script. */

export const ICONS = [
  {
    "name": "home",
    "category": "core",
    "file": "src/home.svg"
  },
  {
    "name": "search",
    "category": "core",
    "file": "src/search.svg"
  },
  {
    "name": "voice-search",
    "category": "core",
    "file": "src/voice-search.svg"
  },
  {
    "name": "microphone",
    "category": "core",
    "file": "src/microphone.svg"
  },
  {
    "name": "camera",
    "category": "core",
    "file": "src/camera.svg"
  },
  {
    "name": "video",
    "category": "core",
    "file": "src/video.svg"
  },
  {
    "name": "image",
    "category": "core",
    "file": "src/image.svg"
  },
  {
    "name": "upload",
    "category": "core",
    "file": "src/upload.svg"
  },
  {
    "name": "plus",
    "category": "core",
    "file": "src/plus.svg"
  },
  {
    "name": "edit",
    "category": "core",
    "file": "src/edit.svg"
  },
  {
    "name": "trash",
    "category": "core",
    "file": "src/trash.svg"
  },
  {
    "name": "check",
    "category": "core",
    "file": "src/check.svg"
  },
  {
    "name": "close",
    "category": "core",
    "file": "src/close.svg"
  },
  {
    "name": "chevron-up",
    "category": "core",
    "file": "src/chevron-up.svg"
  },
  {
    "name": "chevron-down",
    "category": "core",
    "file": "src/chevron-down.svg"
  },
  {
    "name": "chevron-left",
    "category": "core",
    "file": "src/chevron-left.svg"
  },
  {
    "name": "chevron-right",
    "category": "core",
    "file": "src/chevron-right.svg"
  },
  {
    "name": "arrow-up",
    "category": "core",
    "file": "src/arrow-up.svg"
  },
  {
    "name": "arrow-down",
    "category": "core",
    "file": "src/arrow-down.svg"
  },
  {
    "name": "arrow-left",
    "category": "core",
    "file": "src/arrow-left.svg"
  },
  {
    "name": "arrow-right",
    "category": "core",
    "file": "src/arrow-right.svg"
  },
  {
    "name": "filter",
    "category": "core",
    "file": "src/filter.svg"
  },
  {
    "name": "sort",
    "category": "core",
    "file": "src/sort.svg"
  },
  {
    "name": "share",
    "category": "core",
    "file": "src/share.svg"
  },
  {
    "name": "download",
    "category": "core",
    "file": "src/download.svg"
  },
  {
    "name": "dollar-sign",
    "category": "core",
    "file": "src/dollar-sign.svg"
  },
  {
    "name": "print",
    "category": "core",
    "file": "src/print.svg"
  },
  {
    "name": "link",
    "category": "core",
    "file": "src/link.svg"
  },
  {
    "name": "external-link",
    "category": "core",
    "file": "src/external-link.svg"
  },
  {
    "name": "settings",
    "category": "core",
    "file": "src/settings.svg"
  },
  {
    "name": "user",
    "category": "core",
    "file": "src/user.svg"
  },
  {
    "name": "users",
    "category": "core",
    "file": "src/users.svg"
  },
  {
    "name": "bell",
    "category": "core",
    "file": "src/bell.svg"
  },
  {
    "name": "message",
    "category": "core",
    "file": "src/message.svg"
  },
  {
    "name": "package",
    "category": "core",
    "file": "src/package.svg"
  },
  {
    "name": "whatsapp",
    "category": "core",
    "file": "src/whatsapp.svg"
  },
  {
    "name": "calendar",
    "category": "core",
    "file": "src/calendar.svg"
  },
  {
    "name": "clock",
    "category": "core",
    "file": "src/clock.svg"
  },
  {
    "name": "location",
    "category": "core",
    "file": "src/location.svg"
  },
  {
    "name": "phone",
    "category": "core",
    "file": "src/phone.svg"
  },
  {
    "name": "info",
    "category": "core",
    "file": "src/info.svg"
  },
  {
    "name": "warning",
    "category": "core",
    "file": "src/warning.svg"
  },
  {
    "name": "error",
    "category": "core",
    "file": "src/error.svg"
  },
  {
    "name": "success",
    "category": "core",
    "file": "src/success.svg"
  },
  {
    "name": "help",
    "category": "core",
    "file": "src/help.svg"
  },
  {
    "name": "menu",
    "category": "core",
    "file": "src/menu.svg"
  },
  {
    "name": "more-horizontal",
    "category": "core",
    "file": "src/more-horizontal.svg"
  },
  {
    "name": "more-vertical",
    "category": "core",
    "file": "src/more-vertical.svg"
  },
  {
    "name": "eye",
    "category": "core",
    "file": "src/eye.svg"
  },
  {
    "name": "eye-off",
    "category": "core",
    "file": "src/eye-off.svg"
  },
  {
    "name": "lock",
    "category": "core",
    "file": "src/lock.svg"
  },
  {
    "name": "refresh",
    "category": "core",
    "file": "src/refresh.svg"
  },
  {
    "name": "sync",
    "category": "core",
    "file": "src/sync.svg"
  },
  {
    "name": "offline",
    "category": "core",
    "file": "src/offline.svg"
  },
  {
    "name": "wifi-off",
    "category": "core",
    "file": "src/wifi-off.svg"
  },
  {
    "name": "language",
    "category": "core",
    "file": "src/language.svg"
  },
  {
    "name": "accessibility",
    "category": "core",
    "file": "src/accessibility.svg"
  },
  {
    "name": "text-size",
    "category": "core",
    "file": "src/text-size.svg"
  },
  {
    "name": "contrast",
    "category": "core",
    "file": "src/contrast.svg"
  },
  {
    "name": "play",
    "category": "core",
    "file": "src/play.svg"
  },
  {
    "name": "pause",
    "category": "core",
    "file": "src/pause.svg"
  },
  {
    "name": "volume",
    "category": "core",
    "file": "src/volume.svg"
  },
  {
    "name": "speaker",
    "category": "core",
    "file": "src/speaker.svg"
  },
  {
    "name": "badge-verified",
    "category": "core",
    "file": "src/badge-verified.svg"
  },
  {
    "name": "badge-master",
    "category": "core",
    "file": "src/badge-master.svg"
  },
  {
    "name": "badge-award",
    "category": "core",
    "file": "src/badge-award.svg"
  },
  {
    "name": "badge-gi",
    "category": "core",
    "file": "src/badge-gi.svg"
  },
  {
    "name": "badge-coordinator",
    "category": "core",
    "file": "src/badge-coordinator.svg"
  },
  {
    "name": "badge-milestone",
    "category": "core",
    "file": "src/badge-milestone.svg"
  },
  {
    "name": "badge-locked",
    "category": "core",
    "file": "src/badge-locked.svg"
  },
  {
    "name": "handmade-certified",
    "category": "domain",
    "file": "src/handmade-certified.svg"
  },
  {
    "name": "verified-artisan",
    "category": "domain",
    "file": "src/verified-artisan.svg"
  },
  {
    "name": "gi-tagged",
    "category": "domain",
    "file": "src/gi-tagged.svg"
  },
  {
    "name": "made-to-order",
    "category": "domain",
    "file": "src/made-to-order.svg"
  },
  {
    "name": "ready-stock",
    "category": "domain",
    "file": "src/ready-stock.svg"
  },
  {
    "name": "process-video",
    "category": "domain",
    "file": "src/process-video.svg"
  },
  {
    "name": "provenance",
    "category": "domain",
    "file": "src/provenance.svg"
  },
  {
    "name": "handloom-verified",
    "category": "domain",
    "file": "src/handloom-verified.svg"
  },
  {
    "name": "collective-order",
    "category": "domain",
    "file": "src/collective-order.svg"
  },
  {
    "name": "fair-price",
    "category": "domain",
    "file": "src/fair-price.svg"
  },
  {
    "name": "income-statement",
    "category": "domain",
    "file": "src/income-statement.svg"
  },
  {
    "name": "cluster",
    "category": "domain",
    "file": "src/cluster.svg"
  },
  {
    "name": "shg",
    "category": "domain",
    "file": "src/shg.svg"
  },
  {
    "name": "dying-craft",
    "category": "domain",
    "file": "src/dying-craft.svg"
  },
  {
    "name": "weaving",
    "category": "craft",
    "file": "src/weaving.svg"
  },
  {
    "name": "block-printing",
    "category": "craft",
    "file": "src/block-printing.svg"
  },
  {
    "name": "pottery",
    "category": "craft",
    "file": "src/pottery.svg"
  },
  {
    "name": "metalwork",
    "category": "craft",
    "file": "src/metalwork.svg"
  },
  {
    "name": "woodwork",
    "category": "craft",
    "file": "src/woodwork.svg"
  },
  {
    "name": "embroidery",
    "category": "craft",
    "file": "src/embroidery.svg"
  },
  {
    "name": "painting",
    "category": "craft",
    "file": "src/painting.svg"
  },
  {
    "name": "basketry",
    "category": "craft",
    "file": "src/basketry.svg"
  },
  {
    "name": "jewellery",
    "category": "craft",
    "file": "src/jewellery.svg"
  },
  {
    "name": "leather",
    "category": "craft",
    "file": "src/leather.svg"
  },
  {
    "name": "stone",
    "category": "craft",
    "file": "src/stone.svg"
  },
  {
    "name": "bamboo",
    "category": "craft",
    "file": "src/bamboo.svg"
  },
  {
    "name": "charkha-spinner",
    "category": "core",
    "file": "src/charkha-spinner.svg"
  },
  {
    "name": "upload-zone",
    "category": "core",
    "file": "src/upload-zone.svg"
  },
  {
    "name": "badge",
    "category": "core",
    "file": "src/badge.svg"
  }
];
