#!/usr/bin/env bash
# scripts/gen-prod-secrets.sh
# Generates a repo-root .env with strong random secrets for a production
# deploy, starting from .env.example. Same .env is read both by `docker
# compose` (interpolates docker-compose.yml's ${VAR:-dev-default} slots) and
# by a service run directly with `go run` (pkg/config reads these names).
#
# Does NOT set BASE_URL, CORS_ALLOWED_ORIGINS, or any *_ADDR/hostname value --
# those depend on your domain/hosting choice and must be edited by hand after.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$ROOT/.env"

if [[ -f "$ENV_FILE" ]]; then
    echo "Refusing to overwrite existing $ENV_FILE -- remove it first if you want fresh secrets." >&2
    exit 1
fi

cp "$ROOT/.env.example" "$ENV_FILE"

rand_b64() { openssl rand -base64 "$1" | tr -d '\n'; }
rand_hex() { openssl rand -hex "$1"; }
uuid_cluster_id() { python3 -c "import uuid, base64; print(base64.urlsafe_b64encode(uuid.uuid4().bytes).rstrip(b'=').decode())"; }

POSTGRES_PASSWORD="$(rand_hex 24)"
JWT_SECRET="$(rand_b64 48)"          # >=32 bytes raw, base64 gives comfortable margin
S3_ACCESS_KEY="$(rand_hex 12)"
S3_SECRET_KEY="$(rand_hex 24)"
KAFKA_CLUSTER_ID="$(uuid_cluster_id)"

set_var() {
    local name="$1" value="$2"
    # Escape & and / for sed's replacement side.
    local escaped
    escaped=$(printf '%s' "$value" | sed -e 's/[&/\]/\\&/g')
    sed -i "s|^${name}=.*|${name}=${escaped}|" "$ENV_FILE"
}

set_var POSTGRES_PASSWORD "$POSTGRES_PASSWORD"
set_var POSTGRES_DSN "postgres://kalakriti:${POSTGRES_PASSWORD}@postgres:5432/kalakriti?sslmode=disable"
set_var JWT_SECRET "$JWT_SECRET"
set_var S3_ACCESS_KEY "$S3_ACCESS_KEY"
set_var S3_SECRET_KEY "$S3_SECRET_KEY"
set_var AUTH_DEV_OTP_ENABLED "false"
set_var APP_ENV "production"

{
    echo ""
    echo "# Generated by scripts/gen-prod-secrets.sh -- Kafka KRaft cluster id"
    echo "# (docker-compose.yml's kafka service reads this, not pkg/config)."
    echo "KAFKA_CLUSTER_ID=${KAFKA_CLUSTER_ID}"
} >> "$ENV_FILE"

chmod 600 "$ENV_FILE"

echo "Wrote $ENV_FILE with random POSTGRES_PASSWORD, JWT_SECRET, S3_ACCESS_KEY/SECRET_KEY, KAFKA_CLUSTER_ID."
echo "Still needs manual edits before deploying:"
echo "  - BASE_URL              (your public bff URL, e.g. https://api.example.com)"
echo "  - CORS_ALLOWED_ORIGINS  (your Vercel frontend origin, if deployed separately)"
echo "  - AUTH_DEV_OTP_ENABLED must stay false -- there's no real SMS provider wired"
echo "    up yet (pkg's OTP sender is a stub); real OTP delivery needs a provider"
echo "    integration before real users can log in."
