/* Generated by scripts/gen-batch5.mjs — do not hand-edit. */

export const ILLUSTRATIONS = [
  {
    "name": "empty-no-listings",
    "group": "empty",
    "file": "src/empty-no-listings.svg",
    "w": 320,
    "h": 240
  },
  {
    "name": "empty-no-orders",
    "group": "empty",
    "file": "src/empty-no-orders.svg",
    "w": 320,
    "h": 240
  },
  {
    "name": "empty-no-search-results",
    "group": "empty",
    "file": "src/empty-no-search-results.svg",
    "w": 320,
    "h": 240
  },
  {
    "name": "empty-no-notifications",
    "group": "empty",
    "file": "src/empty-no-notifications.svg",
    "w": 320,
    "h": 240
  },
  {
    "name": "empty-offline",
    "group": "empty",
    "file": "src/empty-offline.svg",
    "w": 320,
    "h": 240
  },
  {
    "name": "empty-error",
    "group": "empty",
    "file": "src/empty-error.svg",
    "w": 320,
    "h": 240
  },
  {
    "name": "empty-no-followers",
    "group": "empty",
    "file": "src/empty-no-followers.svg",
    "w": 320,
    "h": 240
  },
  {
    "name": "empty-cart",
    "group": "empty",
    "file": "src/empty-cart.svg",
    "w": 320,
    "h": 240
  },
  {
    "name": "onboard-photograph",
    "group": "onboard",
    "file": "src/onboard-photograph.svg",
    "w": 320,
    "h": 240
  },
  {
    "name": "onboard-description",
    "group": "onboard",
    "file": "src/onboard-description.svg",
    "w": 320,
    "h": 240
  },
  {
    "name": "onboard-buyers-find-you",
    "group": "onboard",
    "file": "src/onboard-buyers-find-you.svg",
    "w": 320,
    "h": 240
  },
  {
    "name": "onboard-paid-directly",
    "group": "onboard",
    "file": "src/onboard-paid-directly.svg",
    "w": 320,
    "h": 240
  },
  {
    "name": "feature-collective-fulfilment",
    "group": "feature",
    "file": "src/feature-collective-fulfilment.svg",
    "w": 320,
    "h": 240
  },
  {
    "name": "feature-provenance",
    "group": "feature",
    "file": "src/feature-provenance.svg",
    "w": 320,
    "h": 240
  },
  {
    "name": "feature-handloom-verification",
    "group": "feature",
    "file": "src/feature-handloom-verification.svg",
    "w": 320,
    "h": 240
  },
  {
    "name": "feature-fair-pricing",
    "group": "feature",
    "file": "src/feature-fair-pricing.svg",
    "w": 320,
    "h": 240
  },
  {
    "name": "process-blockprint-1-carve",
    "group": "process",
    "file": "src/process-blockprint-1-carve.svg",
    "w": 120,
    "h": 120
  },
  {
    "name": "process-blockprint-2-dye",
    "group": "process",
    "file": "src/process-blockprint-2-dye.svg",
    "w": 120,
    "h": 120
  },
  {
    "name": "process-blockprint-3-stamp",
    "group": "process",
    "file": "src/process-blockprint-3-stamp.svg",
    "w": 120,
    "h": 120
  },
  {
    "name": "process-blockprint-4-wash",
    "group": "process",
    "file": "src/process-blockprint-4-wash.svg",
    "w": 120,
    "h": 120
  },
  {
    "name": "process-weaving-1-warp",
    "group": "process",
    "file": "src/process-weaving-1-warp.svg",
    "w": 120,
    "h": 120
  },
  {
    "name": "process-weaving-2-weft",
    "group": "process",
    "file": "src/process-weaving-2-weft.svg",
    "w": 120,
    "h": 120
  },
  {
    "name": "process-weaving-3-beat",
    "group": "process",
    "file": "src/process-weaving-3-beat.svg",
    "w": 120,
    "h": 120
  },
  {
    "name": "process-weaving-4-finish",
    "group": "process",
    "file": "src/process-weaving-4-finish.svg",
    "w": 120,
    "h": 120
  },
  {
    "name": "process-pottery-1-centre",
    "group": "process",
    "file": "src/process-pottery-1-centre.svg",
    "w": 120,
    "h": 120
  },
  {
    "name": "process-pottery-2-throw",
    "group": "process",
    "file": "src/process-pottery-2-throw.svg",
    "w": 120,
    "h": 120
  },
  {
    "name": "process-pottery-3-dry",
    "group": "process",
    "file": "src/process-pottery-3-dry.svg",
    "w": 120,
    "h": 120
  },
  {
    "name": "process-pottery-4-fire",
    "group": "process",
    "file": "src/process-pottery-4-fire.svg",
    "w": 120,
    "h": 120
  },
  {
    "name": "hero-backdrop-tile",
    "group": "hero",
    "file": "src/hero-backdrop-tile.svg",
    "w": 60,
    "h": 60
  },
  {
    "name": "fft-comparison",
    "group": "fft",
    "file": "src/fft-comparison.svg",
    "w": 480,
    "h": 300
  }
];
